include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_const_declarations: warning
    use_build_context_synchronously: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
